# Generated by Django 3.0.4 on 2020-04-26 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BasicCheckup', models.CharField(max_length=100)),
                ('ElectricalCheckup', models.CharField(max_length=100)),
                ('MechanicalCheckup', models.CharField(max_length=100)),
                ('InstallationCheckup', models.CharField(max_length=100)),
                ('ChilledwaterCheckup', models.CharField(max_length=100)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
    ]
